### ISSUE TITLE
MOD stopping on some playfields

### ISSUE THREAD

**Issue by HawkieNorway** [GitHub-TC/EmpyrionNetAPIAccess#1]
I am having the mod working perfectly and on current release (at the time of the post), but on some of the playfields the mod just stops working after a few minutes. If i reload the playfield, it starts working again for a few minutes. No signs of problems in Empyrion logs

**Comment by GitHub-TC** [comment]
I'm watching that too. Our server is 100% CPU under full load. And I see how sometimes the EmpyrionModHost process starts over and over again because there was an exception in one of the mods. I'm doing the whole thing more robust ... and find the errors

In the meantime, try installing the ModLoader, which decouples the mods from the EGS,
https://github.com/GitHub-TC/EmpyrionModHost
